{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/1.3.0/savedstate-1.3.0.module",
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13433626"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-1.3.0.jar",
          "url": "savedstate-desktop-1.3.0.jar",
          "size": 79392,
          "sha512": "89d8a8f0ccc83ee43c65c9eb1e106a6c52077dd6a8401291b057640609b9ec46a36a522e9d258f179f19a2c1740b03580416051fedcd29ed64e74dcf58afa965",
          "sha256": "e78db47f2d82e0f9df90dc9a823a3763684a4b8769b30d7c5365adcf5c37e88f",
          "sha1": "93a03d7f3c778788d849a6421bf93dc48de1d8db",
          "md5": "6eb117ede490f3573e492568dae9a0db"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-1.3.0.jar",
          "url": "savedstate-desktop-1.3.0.jar",
          "size": 79392,
          "sha512": "89d8a8f0ccc83ee43c65c9eb1e106a6c52077dd6a8401291b057640609b9ec46a36a522e9d258f179f19a2c1740b03580416051fedcd29ed64e74dcf58afa965",
          "sha256": "e78db47f2d82e0f9df90dc9a823a3763684a4b8769b30d7c5365adcf5c37e88f",
          "sha1": "93a03d7f3c778788d849a6421bf93dc48de1d8db",
          "md5": "6eb117ede490f3573e492568dae9a0db"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-1.3.0-sources.jar",
          "url": "savedstate-desktop-1.3.0-sources.jar",
          "size": 42521,
          "sha512": "a0b42e164f3ce9e736829796c1813925994eb5b76ee6f75e444f4319dd71e76c2c2683344d7ac42dca23229310bc79931c1186feca991ecc61fa75847e6ccc23",
          "sha256": "be2243ab3cb142b55111dc2643d5c782cbf13cb2ee430c5d9d4749c43137ebb5",
          "sha1": "6782e8abf7c2aba46a824ef0786ab336d69e2d16",
          "md5": "8b36aa1b4be7bad5f5707bc629d9a5df"
        }
      ]
    }
  ]
}